# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 849)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    image: url(:/stuff/money.png);\n"
"    border-image: url(bg_v2.png);\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  background: transparent;\n"
"  color: rgb(86, 86, 86);\n"
"  border-bottom: 1px solid rgb(86, 86, 86);\n"
"}\n"
"\n"
"QPushButton {\n"
"  background-color: #00557f;\n"
"  color: #0f1925;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #00557f;\n"
"  padding: 5px 15px;\n"
"  margin-top: 10px;\n"
"  outline: 0px;\n"
"}\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 80, 1141, 611))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(220, 20, 171, 31))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(86, 86, 86);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 490, 511, 91))
        self.pushButton_2.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(300, 30, 211, 351))
        self.frame_2.setStyleSheet("background-color: #ffff7f;\n"
"border-radius: 16px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(220, 20, 171, 31))
        self.label_4.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(86, 86, 86);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 540, 511, 71))
        self.pushButton_3.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(50, 30, 111, 16))
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(-40, 70, 281, 231))
        self.label_8.setStyleSheet("image: url(:/stuff/money.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(60, 270, 81, 16))
        self.label_11.setObjectName("label_11")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(620, 30, 231, 151))
        self.frame_3.setStyleSheet("background-color: #aaffff;\n"
"border-radius: 16px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(220, 20, 171, 31))
        self.label_5.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(86, 86, 86);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 540, 511, 71))
        self.pushButton_4.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(80, 120, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(50, 10, 131, 111))
        self.label_9.setStyleSheet("image: url(:/stuff/load money.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setGeometry(QtCore.QRect(620, 230, 231, 151))
        self.frame_4.setStyleSheet("background-color: #ff0000;\n"
"border-radius: 16px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(220, 20, 171, 31))
        self.label_6.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(86, 86, 86);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 540, 511, 71))
        self.pushButton_5.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"    \n"
"  color: rgb(255, 255, 255);\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 130, 16))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 151, 151))
        self.label_10.setStyleSheet("image: url(:/stuff/send_money.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_6.raise_()
        self.pushButton_5.raise_()
        self.label_10.raise_()
        self.label_7.raise_()
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(200, 420, 761, 22))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1199, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "🔒Login Page"))
        self.pushButton_2.setText(_translate("MainWindow", "Transaction history"))
        self.pushButton_3.setText(_translate("MainWindow", "Transaction history"))
        self.label.setText(_translate("MainWindow", "Account Balance"))
        self.label_11.setText(_translate("MainWindow", "PKR: 10000"))
        self.pushButton_4.setText(_translate("MainWindow", "Transaction history"))
        self.label_2.setText(_translate("MainWindow", "Load Money"))
        self.pushButton_5.setText(_translate("MainWindow", "Transaction history"))
        self.label_7.setText(_translate("MainWindow", "Transfer Funds"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Account Holder\'s Name"))

# import sys
# from PyQt6.QtWidgets import QApplication, QMainWindow
# from homepage import Ui_MainWindow

# class MyApplication(QMainWindow, Ui_MainWindow):
#     def __init__(self):
#         super().__init__()
#         self.setupUi(self)
#         # Additional setup for your application

# def main():
#     app = QApplication(sys.argv)
#     window = MyApplication()
#     window.show()
#     sys.exit(app.exec())

# if __name__ == "__main__":
#     main()