# Form implementation generated from reading ui file 'type_of_login.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 599)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    image: url(:/stuff/money.png);\n"
"    border-image: url(:/stuff/bg_v2.png);\n"
"}\n"
"QLabel {\n"
"  color: #464d55;\n"
"  font-weight: 600;\n"
"}\n"
"QLabel#heading {\n"
"  color: #0f1925;\n"
"  font-size: 18px;\n"
"  margin-bottom: 10px;\n"
"}\n"
"\n"
"QLabel#subheading {\n"
"  color: #0f1925;\n"
"  font-size: 12px;\n"
"  font-weight: normal;\n"
"  margin-bottom: 10px;\n"
"}\n"
"QLineEdit {\n"
"  background: transparent;\n"
"  color: rgb(86, 86, 86);\n"
"  border-bottom: 1px solid rgb(86, 86, 86);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #8360aa;\n"
"  border: 3px solid #8360aa;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 40, 1151, 491))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"border: 3px solid #000000;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(460, 20, 231, 41))
        self.label_13.setStyleSheet("border: 3px solid #fff;\n"
"  font-size: 30px;")
        self.label_13.setObjectName("label_13")
        self.userButton = QtWidgets.QPushButton(parent=self.frame)
        self.userButton.setGeometry(QtCore.QRect(270, 100, 211, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.userButton.setFont(font)
        self.userButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("user.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.On)
        self.userButton.setIcon(icon)
        self.userButton.setIconSize(QtCore.QSize(90, 90))
        self.userButton.setDefault(False)
        self.userButton.setObjectName("userButton")
        self.adminbutton = QtWidgets.QPushButton(parent=self.frame)
        self.adminbutton.setGeometry(QtCore.QRect(650, 290, 211, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.adminbutton.setFont(font)
        self.adminbutton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("admin.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.On)
        self.adminbutton.setIcon(icon1)
        self.adminbutton.setIconSize(QtCore.QSize(90, 90))
        self.adminbutton.setDefault(False)
        self.adminbutton.setObjectName("adminbutton")
        self.servicebutton = QtWidgets.QPushButton(parent=self.frame)
        self.servicebutton.setGeometry(QtCore.QRect(650, 100, 211, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.servicebutton.setFont(font)
        self.servicebutton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.servicebutton.setIcon(icon)
        self.servicebutton.setIconSize(QtCore.QSize(90, 90))
        self.servicebutton.setDefault(False)
        self.servicebutton.setObjectName("servicebutton")
        self.donationbutton = QtWidgets.QPushButton(parent=self.frame)
        self.donationbutton.setGeometry(QtCore.QRect(270, 290, 211, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.donationbutton.setFont(font)
        self.donationbutton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("donation.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.On)
        self.donationbutton.setIcon(icon2)
        self.donationbutton.setIconSize(QtCore.QSize(80, 80))
        self.donationbutton.setDefault(False)
        self.donationbutton.setObjectName("donationbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1202, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "🔒Login Page"))
        self.label_13.setText(_translate("MainWindow", "Who are you?"))
        self.userButton.setText(_translate("MainWindow", "USER"))
        self.adminbutton.setText(_translate("MainWindow", "ADMIN"))
        self.servicebutton.setText(_translate("MainWindow", "SERVICE"))
        self.donationbutton.setText(_translate("MainWindow", "DONATION\n"
"DRIVE"))

# import sys
# from PyQt6.QtWidgets import QApplication, QMainWindow
# from type_of_login import Ui_MainWindow

# class MyApplication(QMainWindow, Ui_MainWindow):
#     def __init__(self):
#         super().__init__()
#         self.setupUi(self)
#         # Additional setup for your application

# def main():
#     app = QApplication(sys.argv)
#     window = MyApplication()
#     window.show()
#     sys.exit(app.exec())

# if __name__ == "__main__":
#     main()